### ISSUE TITLE
Github marketplace

### ISSUE THREAD

**Issue by fuhuifang** [kt3k/deno_license_checker#33]
Hi, I've been using the following action in my workflow smoothly, but recently it is breaking with error  "Unable to resolve actions. Repository not found: kt3k/license_checker."
```
- name: License Checker
  uses: kt3k/license_checker@v1.0.6
```
So I tried to update it to the following based on https://github.com/marketplace/actions/license-checker
```
- name: License Checker
  uses: kt3k/license_checker_github_action@v1.0.1
```
but it failed with error "Error: unzip is required to install Deno". What is the correct way to use your license checker in a github workflow?

**Comment by fuhuifang** [comment]
Update: `kt3k/license_checker_github_action@v1.0.6` works, but please let me know if there's a better way.

**Comment by kt3k** [comment]
The below should work:

```yaml
run: npx @kt3k/license-checker
```

If you prefer Deno, then:

```yaml
- uses: denoland/setup-deno@v1
  with:
    deno-version: v1.x
- run: deno run --allow-read https://deno.land/x/license_checker@v3.2.2/main.ts
```
